project:
  type: book
  output-dir: _book

book:
  title: "2x your Lifetime Customer Value with Salesforce Commerce and Revenue Cloud"
  subtitle: "A comprehensive guide for implementing and optimizing Salesforce Commerce Cloud"
  author:
    - Naj Irshad
    - Shantanu Bhardwaj
    - Justin Leader
  publisher: "Stack Intelligence"
  date: "2023"
  chapters:
    - index.md
    - 00a_Introduction.md
    - 01.md
    - 02.md
    - 03.md
    - 04.md
    - 05.md
    - 06.md
    - 07.md
    - 08.md
    - 09.md
    - 10.md
    - 11.md
    - 12.md

format:
  pdf:
    documentclass: scrreprt
    papersize: letter
    fontsize: 11pt
    toc: true
    toc-title: "CONTENTS"
    number-sections: true
    colorlinks: true
    linkcolor: blue
    geometry:
      - margin=1in
    fig-width: 6
    fig-height: 4
    highlight-style: github
    log-level: INFO
    log-file: "templates.log"
    include-in-header: 
      text: |
        \definecolor{primarycolor}{HTML}{2a368e}
        \definecolor{secondarycolor}{HTML}{EB7527}
        \definecolor{tertiarycolor}{HTML}{7EA0C6}

brand: stack-intelligence